[package]
name = "solana-votor"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana-votor"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
dev-context-only-utils = ["solana-runtime/dev-context-only-utils"]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "solana-accounts-db/frozen-abi",
    "solana-bloom/frozen-abi",
    "solana-ledger/frozen-abi",
    "solana-runtime/frozen-abi",
    "solana-sdk/frozen-abi",
    "solana-vote/frozen-abi",
    "solana-vote-program/frozen-abi",
]

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
bitvec = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true, features = ["rayon", "raw-api"] }
etcd-client = { workspace = true, features = ["tls"] }
itertools = { workspace = true }
log = { workspace = true }
qualifier_attr = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_derive = { workspace = true }
solana-accounts-db = { workspace = true }
solana-bloom = { workspace = true }
solana-bls-signatures = { workspace = true, features = ["solana-signer-derive"] }
solana-entry = { workspace = true }
solana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
solana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
solana-gossip = { workspace = true }
solana-ledger = { workspace = true }
solana-logger = { workspace = true }
solana-measure = { workspace = true }
solana-metrics = { workspace = true }
solana-pubkey = { workspace = true }
solana-rpc = { workspace = true }
solana-runtime = { workspace = true }
solana-sdk = { workspace = true }
solana-vote = { workspace = true }
solana-vote-program = { workspace = true }
solana-votor-messages = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
solana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
test-case = { workspace = true }

[lints]
workspace = true
